export const Department = {
  FETAL: "fetal",
  INFANT: "infant",
  TODDLER: "toddler",
  KINDERGARTEN: "kindergarten",
  ELEMENTARYYOUNG: "elementaryYoung",
  ELEMENTARY: "elementary",
  JUNIOR: "junior",
  MIDDLE: "middle",
  MIDDLEHIGH: "middleHigh",
  HIGH: "high",
  GONGREUNGYOUNGKINDER: "gongreungYoungKinder",
  GONGREUNGELEMENTARYYOUNG: "gongreungElementaryYoung",
  GONGREUNGELEMENTARY: "gongreungElementary",
  GONGREUNGMIDDLE: "gongreungMiddle",
  GONGREUNGHIGH: "gongreungHigh",
  ENGLISHYOUNGKINDER: "englishYoungKinder",
  ENGLISHELEMENTARYYOUNG: "englishElementaryYoung",
  ENGLISHELEMENTARY: "englishElementary",
  ENGLISHMIDDLEHIGH: "englishMiddleHigh",
  LOVE: "love",
  YOUTH: "youth",
  ETC: "etc",
} as const;

export const Position = {
  PASTOR: "pastor",
  EVANGELIST: "evangelist",
  ELDER: "elder",
  TEACHER: "teacher",
  ETC: "etc",
} as const;
