import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Toaster } from "@/app/components/ui/toaster";
import { headers } from "next/headers";
import { useAuthStore } from "@/store/useAuthStore";
import { useEffect } from "react";
// import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

// const pretendard = localFont({ src: "fonts/Pretendard-Regular.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <div className="flex flex-col w-screen min-h-screen">
          <Header />
          <main className="">
            <div className="py-20 overflow-y-auto">{children}</div>
          </main>
          <Footer />
        </div>

        <Toaster />
      </body>
    </html>
  );
}
